### ISSUE TITLE
您好，想请教一个代码问题

### ISSUE THREAD

**Issue by lsxwtt** [sjtuplayer/anomalydiffusion#13]
我尝试运行main.py代码，运行到加载模型时，出现以下错误
ModuleNotFoundError: No module named 'taming.modules.vqvae'

错误代码定位-anomalydiffusion-master\ldm\models\autoencoder.py中有from taming.modules.vqvae.quantize import VectorQuantizer2 as VectorQuantizer，可是 taming.modules文件夹并没有可导入的文件，请问这是怎么回事呀

**Comment by boxbox2** [comment]
他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer

**Comment by lsxwtt** [comment]
> 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer

可是taming.modules文件夹下面只有一个autoencoder文件夹，没有vqvae.quantize呀

**Comment by lsxwtt** [comment]
> 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer

**Comment by lsxwtt** [comment]
> 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer

好的，谢谢啦

**Comment by szgy66** [comment]
> > 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer
> 
> 好的，谢谢啦

你好，你改好了吗？taming文件夹只有一个vgg.pth，没有taming.modules.vqvae.quantize啊

**Comment by lsxwtt** [comment]
> > > 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer
> > 
> > 
> > 好的，谢谢啦
> 
> 你好，你改好了吗？taming文件夹只有一个vgg.pth，没有taming.modules.vqvae.quantize啊
这里的taming是一个python库，需要pip安装

**Comment by szgy66** [comment]
> > > > 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer
> > > 
> > > 
> > > 好的，谢谢啦
> > 
> > 
> > 你好，你改好了吗？taming文件夹只有一个vgg.pth，没有taming.modules.vqvae.quantize啊
> > 这里的taming是一个python库，需要pip安装

好嘞，感谢，已经开始跑了。但是我有一个疑惑想请教一下。训练缺陷图像生成的时候依赖name-anomaly.txt，他包含了所有MVTec的数据集，如果我只想训练一个类别，比如“bottle”,这个可以吗，把所有MVTec的数据集都放一起的意义是啥呢

**Comment by sjtuplayer** [comment]
因为需要训练spatial encoder来编码位置信息，为了防止过拟合，因此所有类别一起训练同一个spatial encoder

**Comment by sjtuplayer** [comment]
> > > > > 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer
> > > > 
> > > > 
> > > > 好的，谢谢啦
> > > 
> > > 
> > > 你好，你改好了吗？taming文件夹只有一个vgg.pth，没有taming.modules.vqvae.quantize啊
> > > 这里的taming是一个python库，需要pip安装
> 
> 好嘞，感谢，已经开始跑了。但是我有一个疑惑想请教一下。训练缺陷图像生成的时候依赖name-anomaly.txt，他包含了所有MVTec的数据集，如果我只想训练一个类别，比如“bottle”,这个可以吗，把所有MVTec的数据集都放一起的意义是啥呢

因为需要训练spatial encoder来编码位置信息，为了防止过拟合，因此所有类别一起训练同一个spatial encoder

**Comment by szgy66** [comment]
> > > > > > 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer
> > > > > 
> > > > > 
> > > > > 好的，谢谢啦
> > > > 
> > > > 
> > > > 你好，你改好了吗？taming文件夹只有一个vgg.pth，没有taming.modules.vqvae.quantize啊
> > > > 这里的taming是一个python库，需要pip安装
> > 
> > 
> > 好嘞，感谢，已经开始跑了。但是我有一个疑惑想请教一下。训练缺陷图像生成的时候依赖name-anomaly.txt，他包含了所有MVTec的数据集，如果我只想训练一个类别，比如“bottle”,这个可以吗，把所有MVTec的数据集都放一起的意义是啥呢
> 
> 因为需要训练spatial encoder来编码位置信息，为了防止过拟合，因此所有类别一起训练同一个spatial encoder

虽然文章没明确说这个作用，但是结合附录B和C.1应该是这个目的。我i还有个问题，如果我想训练自己的缺陷，我可以把自己所有缺陷种类替换name-anomaly.txt的内容吧，或者加上我自己缺陷

**Comment by sjtuplayer** [comment]
是的，需要替换name-anomaly.txt为自己的sample_name和anomaly_name，并保持数据集格式与mvtec一致即可

**Comment by sjtuplayer** [comment]
> > > > > > > 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer
> > > > > > 
> > > > > > 
> > > > > > 好的，谢谢啦
> > > > > 
> > > > > 
> > > > > 你好，你改好了吗？taming文件夹只有一个vgg.pth，没有taming.modules.vqvae.quantize啊
> > > > > 这里的taming是一个python库，需要pip安装
> > > 
> > > 
> > > 好嘞，感谢，已经开始跑了。但是我有一个疑惑想请教一下。训练缺陷图像生成的时候依赖name-anomaly.txt，他包含了所有MVTec的数据集，如果我只想训练一个类别，比如“bottle”,这个可以吗，把所有MVTec的数据集都放一起的意义是啥呢
> > 
> > 
> > 因为需要训练spatial encoder来编码位置信息，为了防止过拟合，因此所有类别一起训练同一个spatial encoder
> 
> 虽然文章没明确说这个作用，但是结合附录B和C.1应该是这个目的。我i还有个问题，如果我想训练自己的缺陷，我可以把自己所有缺陷种类替换name-anomaly.txt的内容吧，或者加上我自己缺陷

是的，需要替换name-anomaly.txt为自己的sample_name和anomaly_name，并保持数据集格式与mvtec一致即可

**Comment by lsxwtt** [comment]
> > > > > > > 他这个代码版本变了，你把他改成from taming.modules.vqvae.quantize import VectorQuantizer
> > > > > > 
> > > > > > 
> > > > > > 好的，谢谢啦
> > > > > 
> > > > > 
> > > > > 你好，你改好了吗？taming文件夹只有一个vgg.pth，没有taming.modules.vqvae.quantize啊
> > > > > 这里的taming是一个python库，需要pip安装
> > > 
> > > 
> > > 好嘞，感谢，已经开始跑了。但是我有一个疑惑想请教一下。训练缺陷图像生成的时候依赖name-anomaly.txt，他包含了所有MVTec的数据集，如果我只想训练一个类别，比如“bottle”,这个可以吗，把所有MVTec的数据集都放一起的意义是啥呢
> > 
> > 
> > 因为需要训练spatial encoder来编码位置信息，为了防止过拟合，因此所有类别一起训练同一个spatial encoder
> 
> 虽然文章没明确说这个作用，但是结合附录B和C.1应该是这个目的。我i还有个问题，如果我想训练自己的缺陷，我可以把自己所有缺陷种类替换name-anomaly.txt的内容吧，或者加上我自己缺陷

您好，请问您使用自己的数据集进行训练了吗？
