### ISSUE TITLE
生成图片对（mask对应）的成功率大概有多少？

### ISSUE THREAD

**Issue by xuyu666** [sjtuplayer/anomalydiffusion#15]
作者您好：
我下载了您发布的测试结果，简单观察了其中几组，但是有些疑惑。您那边测试的话，大概抽几张卡能成功一次。

**Comment by sjtuplayer** [comment]
生成mask时，根据mask的一些形态指定了规则进行筛选，不同种类的缺陷类别成功概率不一，大部分可以一次成功，少部分需要几次
根据mask生成缺陷图时，是没有筛选的，直接生成的，因此生成结果中会出现一些不是很好的效果

**Comment by xuyu666** [comment]
谢谢您的回复。那假如我想针对“hazelnut\crack“这个情况进行生成，应如何正确使用推理代码。是采用下方图片的来执行么~
![image](https://github.com/sjtuplayer/anomalydiffusion/assets/49869475/88252f4d-6d38-42c0-98fb-4d00e1d723d8)

**Comment by sjtuplayer** [comment]
> 您的回复。那假如我想针对“hazelnut\crack“这个情况进行生成，应如何正确使用推理代码。是采用下方图

生成模型inference的代码还未开放，预计今天会上传

**Comment by xuyu666** [comment]
酷的！
