### ISSUE TITLE
ModuleNotFoundError: No module named 'taming.modules.vqvae'

### ISSUE THREAD

**Issue by moxiaoli9** [sjtuplayer/anomalydiffusion#16]
Nice work! I wonder if the vqvae.py is missing in taming.modules when I was trying to run main.py?

**Comment by xuyu666** [comment]
![企业微信截图_17096964247583](https://github.com/sjtuplayer/anomalydiffusion/assets/49869475/917e2303-bbc1-4c53-ac9f-a5fa3f8d0bed)

Replace quantize.py on your machine with this file
https://github.com/CompVis/taming-transformers/blob/master/taming/modules/vqvae/quantize.py
