### ISSUE TITLE
No such file or directory: 'logs/anomaly-checkpoints/checkpoints/spatial_encoder.pt'

### ISSUE THREAD

**Issue by xuyu666** [sjtuplayer/anomalydiffusion#20]
作者您好：
很高兴看到您发布了推理代码~

我在运行推理代码过程中遇到这个错误，貌似您提供的**anomaly-checkpoints**缺失了**spatial_encoder.pt**。或许其需要训练来获得，但为了快速验证论文效果，可能我也想获得一个预训练模型，先看看具体效果。请问可以提供下么，或者是我某个步骤遗漏了。

**Comment by sjtuplayer** [comment]
这是命名的问题，将之前下载的ht_encoder改名为spatial_encoder即可

**Comment by xuyu666** [comment]
![image](https://github.com/sjtuplayer/anomalydiffusion/assets/49869475/5655ff33-0e78-42b2-b362-6f4715076b7a)
好的哈，谢谢作者快速的回复~
PS: 压缩包内部的文件夹的名称拼写貌似不对。（可能导致不易发现的错误）

**Comment by sjtuplayer** [comment]
感谢提醒，已修改
