### ISSUE TITLE
"x" why is [1,256,256,256]?how to solve it ?

### ISSUE THREAD

**Issue by boxbox2** [sjtuplayer/anomalydiffusion#23]
![image](https://github.com/sjtuplayer/anomalydiffusion/assets/56194614/166e29c6-2c71-416f-ab67-e6f96e85cb24)

![image](https://github.com/sjtuplayer/anomalydiffusion/assets/56194614/f9c1778f-395a-48ad-a6c6-aa2b3bada685)

**Comment by OceanWong1991** [comment]
RuntimeError: Given groups=1, weight of size [64, 3, 3, 3], expected input[1, 256, 256, 256] to have 3 channels, but got 256 channels instead
same...
@sjtuplayer

**Comment by OceanWong1991** [comment]
Add more detials,
when I run this command:
CUDA_VISIBLE_DEVICES=0 python main.py --spatial_encoder_embedding --data_enhance --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder+embedding.yaml -t --actual_resume /home/ai/projects/anomalydiffusion/models/ldm/text2img-large/model.ckpt -n test --gpus 0 --init_word anomaly  --mvtec_path=/home/ai//mvtec_anomaly_detection

**Comment by sjtuplayer** [comment]
Maybe you should change batch size from 1 to a number larger than 1(e.g., 2 or 4). I think this is caused by some torch.squeeze() operation.
