### ISSUE TITLE
您好，想请教一个关于训练的问题

### ISSUE THREAD

**Issue by lsxwtt** [sjtuplayer/anomalydiffusion#25]
在您提供的推理代码generate_with_mask.py中，生成异常图像掩码对加载了spatial_encoder.pt和embeddings.pt两个权重模型，如果更换数据集进行训练的话，请问运行python main.py可以生成这个两个权重模型吗？还是spatial_encoder.pt是通过运行python main.py得到的，embeddings.pt是通过运行python train_mask.py得到的？

**Comment by sjtuplayer** [comment]
generate_with_mask.py中的spatial_encoder和embeddings权重都是由main.py生成的，train_mask.py只用于generate_mask.py

**Comment by lsxwtt** [comment]
感谢您的回复，请问仅加载txt2img-1p4B-finetune-encoder+embedding.yaml就可以生成spatial_encoder和embeddings两个权重吗？还是生成embeddings.pt需要加载cofigs/autoencoder中的配置文件？

**Comment by sjtuplayer** [comment]
直接按照readme运行main.py就可以生成spatial_encoder和embeddings了

**Comment by lsxwtt** [comment]
> 直接按照readme运行main.py就可以生成spatial_encoder和embeddings了

好的，感谢您的指点

**Comment by lsxwtt** [comment]
> 直接按照readme运行main.py就可以生成spatial_encoder和embeddings了

好的，感谢您的指导
