### ISSUE TITLE
Error Encountered When Training Generative Network

### ISSUE THREAD

**Issue by seungmi-oh** [sjtuplayer/anomalydiffusion#26]
Hello. 

I wanted to thank you for sharing the codes and data with detailed explanations; it's been incredibly helpful.

I've been trying to train the generative network following the instructions in the readme.md file. However, I've run into an issue: it seems that "taming.modules.vqvae" is missing, causing an error.

Could you please provide some insight into resolving this? Your assistance would be greatly appreciated.

Thanks in advance for your help.

**Comment by lsz23** [comment]
I have encountered the same problem. How did you solve it?
