### ISSUE TITLE
nvcc fatal   : Unsupported gpu architecture 'compute_86'

### ISSUE THREAD

**Issue by bat1115** [sjtuplayer/anomalydiffusion#28]
在RTX 4090上执行main.py时，遇到nvcc fatal   : Unsupported gpu architecture 'compute_86' error，请问如何解决。

**Comment by bat1115** [comment]
还有，请问能否使用多卡训练？如果可以的话如何使用多卡进行训练呢，我使用多卡的时候老是卡死。下面是我的运行代码：
CUDA_VISIBLE_DEVICES=0,1 python main.py --spatial_encoder_embedding --data_enhance --base configs/latent-diffusion/txt2img-1p4B-finetune-encoder+embedding.yaml -t --actual_resume models/ldm/text2img-large/model.ckpt -n test --gpus 0,1 --init_word anomaly --mvtec_path=$path_to_mvtec_dataset

**Comment by bat1115** [comment]
> 在RTX 4090上执行main.py时，遇到nvcc fatal : Unsupported gpu architecture 'compute_86' error，请问如何解决。

将pytorch升级到与RTX 4090的8.9算力匹配的版本后，出现了下面的错误，nvcc fatal   : Value 'c++17' is not defined for option 'std'，不知道您有没有遇到过这个问题？

**Comment by sjtuplayer** [comment]
you can try using gcc==7

**Comment by bat1115** [comment]
> you can try using gcc==7
将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！

**Comment by lsxwtt** [comment]
> > you can try using gcc==7
> > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！

您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀

**Comment by bat1115** [comment]
> > > you can try using gcc==7
> > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> 
> 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀

pytorch=1.12，cuda=11.3，ninja=1.11

**Comment by bat1115** [comment]
> > > you can try using gcc==7
> > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> 
> 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀

pytorch=1.12，cuda=11.3，ninja=1.11，把pytorch升级到与RTX 4090的8.9算力匹配的版本后有了新的报错，没能解决。把版本恢复到作者提供的版本后，通过限制4090的算力成功跑了起来。

**Comment by lsxwtt** [comment]
> > > > you can try using gcc==7
> > > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> > 
> > 
> > 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀
> 
> pytorch=1.12，cuda=11.3，ninja=1.11，把pytorch升级到与RTX 4090的8.9算力匹配的版本后有了新的报错，没能解决。把版本恢复到作者提供的版本后，通过限制4090的算力成功跑了起来。

请问您使用的是ubantu系统吗？系统安装的cuda也是11.3吗

**Comment by bat1115** [comment]
> > > > > you can try using gcc==7
> > > > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> > > 
> > > 
> > > 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀
> > 
> > 
> > pytorch=1.12，cuda=11.3，ninja=1.11，把pytorch升级到与RTX 4090的8.9算力匹配的版本后有了新的报错，没能解决。把版本恢复到作者提供的版本后，通过限制4090的算力成功跑了起来。
> 
> 请问您使用的是ubantu系统吗？系统安装的cuda也是11.3吗

nvidia-smi显示的版本是12.2，nvcc -V显示的版本是10.1，你可以把nvcc -V的版本升级到和4090匹配试试，也许这样能使用8.9的算力

**Comment by lsxwtt** [comment]
> > > > > > you can try using gcc==7
> > > > > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> > > > 
> > > > 
> > > > 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀
> > > 
> > > 
> > > pytorch=1.12，cuda=11.3，ninja=1.11，把pytorch升级到与RTX 4090的8.9算力匹配的版本后有了新的报错，没能解决。把版本恢复到作者提供的版本后，通过限制4090的算力成功跑了起来。
> > 
> > 
> > 请问您使用的是ubantu系统吗？系统安装的cuda也是11.3吗
> 
> nvidia-smi显示的版本是12.2，nvcc -V显示的版本是10.1，你可以把nvcc -V的版本升级到和4090匹配试试，也许这样能使用8.9的算力

好的，非常感谢，还有个问题想要请教一下，请问推理代码中，embedding.pt和spatial_encoder.pt各自代表什么呀？我直接运行main.py，这两个训练好的模型保存在哪里呀？

**Comment by bat1115** [comment]
> > > > > > > you can try using gcc==7
> > > > > > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> > > > > 
> > > > > 
> > > > > 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀
> > > > 
> > > > 
> > > > pytorch=1.12，cuda=11.3，ninja=1.11，把pytorch升级到与RTX 4090的8.9算力匹配的版本后有了新的报错，没能解决。把版本恢复到作者提供的版本后，通过限制4090的算力成功跑了起来。
> > > 
> > > 
> > > 请问您使用的是ubantu系统吗？系统安装的cuda也是11.3吗
> > 
> > 
> > nvidia-smi显示的版本是12.2，nvcc -V显示的版本是10.1，你可以把nvcc -V的版本升级到和4090匹配试试，也许这样能使用8.9的算力
> 
> 好的，非常感谢，还有个问题想要请教一下，请问推理代码中，embedding.pt和spatial_encoder.pt各自代表什么呀？我直接运行main.py，这两个训练好的模型保存在哪里呀？

embedding.pt可以查看AnomalyDiffusion/ldm/modules/embedding_manager2.py中的save( )函数，spatial_encoder.pt保存的是spatial_encoder_model的参数，这两个权重文件可以在AnomalyDiffusion/logs/anomaly-checkpoints目录下找到。

**Comment by lsxwtt** [comment]
> > > > > > > > you can try using gcc==7
> > > > > > > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> > > > > > 
> > > > > > 
> > > > > > 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀
> > > > > 
> > > > > 
> > > > > pytorch=1.12，cuda=11.3，ninja=1.11，把pytorch升级到与RTX 4090的8.9算力匹配的版本后有了新的报错，没能解决。把版本恢复到作者提供的版本后，通过限制4090的算力成功跑了起来。
> > > > 
> > > > 
> > > > 请问您使用的是ubantu系统吗？系统安装的cuda也是11.3吗
> > > 
> > > 
> > > nvidia-smi显示的版本是12.2，nvcc -V显示的版本是10.1，你可以把nvcc -V的版本升级到和4090匹配试试，也许这样能使用8.9的算力
> > 
> > 
> > 好的，非常感谢，还有个问题想要请教一下，请问推理代码中，embedding.pt和spatial_encoder.pt各自代表什么呀？我直接运行main.py，这两个训练好的模型保存在哪里呀？
> 
> embedding.pt可以查看AnomalyDiffusion/ldm/modules/embedding_manager2.py中的save( )函数，spatial_encoder.pt保存的是spatial_encoder_model的参数，这两个权重文件可以在AnomalyDiffusion/logs/anomaly-checkpoints目录下找到。

谢谢，请问这个epoch最大是多少呀？从哪里可以改呀？

**Comment by bat1115** [comment]
> > > you can try using gcc==7
> > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> 
> 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀

谢谢，请问这个epoch最大是多少呀？从哪里可以改呀？
Reply: 
![image](https://github.com/sjtuplayer/anomalydiffusion/assets/58722076/1c589302-b47e-4ad1-91fb-ba390425e59c)

**Comment by lsxwtt** [comment]
> > > > you can try using gcc==7
> > > > 将原本的gcc=9.4降到9.3，并且通过export TORCH_CUDA_ARCH_LIST="7.5"命令将GPU算力降到7.5后，成功在4090上跑起来了，感谢！
> > 
> > 
> > 您好，我也遇到了这个问题，请问您用的pytorch，cuda，ninja版本是什么呀
> 
> 谢谢，请问这个epoch最大是多少呀？从哪里可以改呀？ Reply: ![image](https://private-user-images.githubusercontent.com/58722076/324235851-1c589302-b47e-4ad1-91fb-ba390425e59c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2OTE4MTgsIm5iZiI6MTcxMzY5MTUxOCwicGF0aCI6Ii81ODcyMjA3Ni8zMjQyMzU4NTEtMWM1ODkzMDItYjQ3ZS00YWQxLTkxZmItYmEzOTA0MjVlNTljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIxVDA5MjUxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiOTA2YzY1NDVmNjRkYWEwODA1YjI1ZDMyNTdhN2FjMzU2M2VmOGVkYmI1N2ZmODE4MDZhY2RlZTFiMzYwZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tTA_YL4E5Xpimy6QCUfZAr9J5peZVSipte8chZcklzM)

啊，300000个epoch，请问您一下，我训练1000个epoch之后，\anomalydiffusion\logs\anomaly-checkpoints\checkpoints文件夹下有epoch=000578.ckpt，last.ckpt，请问这两个就是对应的embedding.pt，spatial_encoder.pt吗
