### ISSUE TITLE
tensor

### ISSUE THREAD

**Issue by SorryMaker666** [sjtuplayer/anomalydiffusion#29]
![5fc9426912daa45bca4331025a47844f](https://github.com/sjtuplayer/anomalydiffusion/assets/101252764/04e6cde4-d390-4751-ba80-d431250b53e8)
您好！请问我该怎么解决这个问题，让tensor不在cpu上处理

**Comment by KenLUoHere** [comment]
I got the same question, have you done with it?

**Comment by KenLUoHere** [comment]
I've done it by changing the main.py, for adding the model to trainer and initialize model in fit part, wish I can help you`try:
                device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
                model = model.to(device)
           #     if isinstance(data, list):
            #        data = [item.to(device) if isinstance(item, torch.Tensor) else item for item in data]
            #    else:
            #        data = data.to(device)

                trainer.fit(model, data)
            except Exception:
                model = model.to(device)
                trainer.model = model # 设置trainer的model属性
                melk()
                raise`

**Comment by KenLUoHere** [comment]
I finished the problem by initialize model and trainer before training:`            try:
                device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
                model = model.to(device)
           #     if isinstance(data, list):
            #        data = [item.to(device) if isinstance(item, torch.Tensor) else item for item in data]
            #    else:
            #        data = data.to(device)

                trainer.fit(model, data)
            except Exception:
                model = model.to(device)
                trainer.model = model # 设置trainer的model属性
                melk()
                raise`
