### ISSUE TITLE
请问代码啥时候开源~

### ISSUE THREAD

**Issue by xuyu666** [sjtuplayer/anomalydiffusion#3]
作者您好：
阅读您的论文后，对文章内容很感兴趣，想问下啥时候可以开源下代码或Demo？

**Comment by sjtuplayer** [comment]
感谢对我们工作的关注！我们会在一月底陆续开放我们的数据和代码~

**Comment by littledeep** [comment]
Thanks for the nice work! I am looking forward your code.

**Comment by leixiaoning** [comment]
1

**Comment by YuQianzi** [comment]
1

**Comment by sjtuplayer** [comment]
The training code has been updated. The inference code and generated data will be uploaded soon. Thanks for your patience!

**Comment by CVKim** [comment]
The training code being open has been very educational!
Could you let me know when the inference code will be released??
