### ISSUE TITLE
Is "caption" meaningful for the model?

### ISSUE THREAD

**Issue by p890040** [sjtuplayer/anomalydiffusion#30]
Hi there,

I've noticed that within the inputs of the model, the "caption" is randomly selected from the strings in ldm/data/personalized.py 
 => imagenet_templates_small.

However, given that this selection process is random, I'm curious about the significance of this caption for the model. Since both training and inference processes utilize this caption as one of the inputs, it's likely to have an impact on the model's output. Therefore, I find it a bit puzzling and would like to confirm with you, if I may be misunderstanding something.

**Comment by sjtuplayer** [comment]
I think the caption do not matter. Since the caption number is limited. The captions in inference time have been used in the training time. So, it would not influence the results too much. It is originally designed for the generation diversity.
