### ISSUE TITLE
What significance does initializer_words have?

### ISSUE THREAD

**Issue by lu1zero9** [sjtuplayer/anomalydiffusion#32]
Hello, I have a question I'd like to ask you. In the embedding_manager2.py code, there's an addition of initializer_words. What is the significance of this? Is it intended to incorporate anomaly text information into the embedding, or does it serve another purpose?

**Comment by zjuPeco** [comment]
This parameter is from text inversion. You can refer to [https://github.com/rinongal/textual_inversion/issues/19](https://github.com/rinongal/textual_inversion/issues/19) for detailed explanation.
