### ISSUE TITLE
mask generation

### ISSUE THREAD

**Issue by TerryMelody** [sjtuplayer/anomalydiffusion#40]
In generate_mask.py, can I use "logs/anomaly-checkpoints/checkpoints/embeddings.pt"(the results of main.py) instead of “logs/mask-checkpoints/cable-bent_wire/checkpoints/embeddings.pt”（the results of train_mask.py)?  I don't know the functions of train_mask.py. It seems that only main.py can learn the mask generation.

**Comment by DonghoonPark12** [comment]
In generate_mask.py It use “logs/mask-checkpoints/cable-bent_wire/checkpoints/embeddings.pt” which is made by train_mask.py.

train_mask.py generate embedding.pt <-- ('sample'=True, 'inpaint'=False)
main.py genereate embedding.pt <-- ('sample'=False, 'inpaint'=True)

Notice me any question.

**Comment by CVKim** [comment]
@DonghoonPark12 , @TerryMelody , @sjtuplayer 

So, if I want to augment the mvtec-ad dataset to create a new dataset, and then train a model to generate masks using the new dataset, should I use the run_mvtec.py code to train the model with train_mask.py and generate the embedding.pt file for the new dataset? After that, should I generate images using the generated_mask.py and generated_with_mask.py codes?

I'm also confused, just like the previous questioner!

Is using run_mvtec.py the correct way to train a custom dataset and then use the trained .pt file to generate images??

**Comment by sjtuplayer** [comment]
> ment the mvtec-ad dataset to create a new dataset, and then train a model to generate masks using the new dataset, should I use the run_mvtec.py code to train the model with train_mask.py and generate the embedding.pt file for the new dataset? After that, should I generate images using the generated_mask.py and generated_with_mask.py codes?
> 
> I'm also confused, just like the previous questioner!
> 
> Is using run_mvtec.py the correct way to train a custom dataset and then use the trained .pt file to generate images??

Yes, you are right. For a new dataset, you should first train the whole model by:
python main.py
After that, you can run run-mvtec.py, which will generate the mask and then the anomaly images.

**Comment by CVKim** [comment]
@DonghoonPark12 , @sjtuplayer , @TerryMelody 

After training my custom dataset using main.py, where should I place the generated checkpoint files, such as embeddings.pt and spatial_encoder.pt, and how should I use them?

After training my custom dataset with main.py and generating the .pt files, do I need to further train train_mask.pt using the run-mvtec.py code?

I’m a bit confused about the difference in roles between main.py and run-mvtec.py (train_mask.py). How should I correctly use the checkpoints created from main.py?

Could you please provide more details on how to use the checkpoint files created from main.py?

----
I trained a new custom dataset using main.py and then moved the generated embedding.pt and spatial.pt files to the logs/anomaly-checkpoint folder. However, after running run-mvtec.py, the images were not generated correctly, so I’m asking for help!

Below is a picture of the images generated in the mask-checkpoint folder during the train_mask.py process after running run-mvtec.py.
----

![image](https://github.com/user-attachments/assets/2f0ccf55-40fb-4e58-b1fe-ca9da01365c0)
