### ISSUE TITLE
Some confusion about run-mvtec.py

### ISSUE THREAD

**Issue by bat1115** [sjtuplayer/anomalydiffusion#42]
When I run run-mvtec.py, I can't stop it by ctrl+c, do you have any solution?

**Comment by bat1115** [comment]
> You assign k = 8 tokens for anomaly embedding, but num_vectors_per_token = 4 in your code.

And when I run run-mvtec.py, I can't stop it by ctrl+c, do you have any solution?

**Comment by sjtuplayer** [comment]
You can use 'sleep' between each two os.system() operation. Then, you can stop it with tow continuous 'ctrl+c' operations.
