### ISSUE TITLE
Generated images in uploaded dataset

### ISSUE THREAD

**Issue by TerryMelody** [sjtuplayer/anomalydiffusion#45]
Hello dear authors, this is an impressive job! Thanks for your contributions. But I'm a little confused about some generated results. For example, in your uploaded generated dataset, 'hazelnut_hole' 10.jpg-12.jpg, there is no hole in the generated images. Are these unusual cases? Because I noticed that most of the cases are good as showed in the bottom row.
![image](https://github.com/sjtuplayer/anomalydiffusion/assets/57710177/83a3f809-9f85-4f34-b07a-ac29af1f9ede)
![image](https://github.com/sjtuplayer/anomalydiffusion/assets/57710177/c1fddba3-7a61-4aaf-8f1b-9a37316481b4)
![image](https://github.com/sjtuplayer/anomalydiffusion/assets/57710177/84baba99-c2e0-4166-90b9-de7fb0465e7d)

**Comment by sjtuplayer** [comment]
Hi~ There are some failure cases in the generated data as you mentioned. You can eliminate them for better anomaly detection performance.
