### ISSUE TITLE
Method of generate Anomaly images other than 256x256

### ISSUE THREAD

**Issue by f29739** [sjtuplayer/anomalydiffusion#47]
Hello, thanks for your great work.
Sorry to ask something so elementary,
is there a way to output image sizes other than 256x256 with this anomaly generation model?
Thank you so much for your help.

**Comment by PonyPinkPie** [comment]
> You can try switching to a newer Stable Diffusion model like SD-XL.

I tried to adjust the code to achieve larger training sizes, but failed. Is there any examples showing how to do it?

**Comment by DqqHns** [comment]
我也想通过调整代码去生成512*512的，我也不清楚该怎么修改，可以请教一下吗？
256*256生成我自己的数据集的效果还是很不错的
