### ISSUE TITLE
您好，想请教一个问题！

### ISSUE THREAD

**Issue by lsxwtt** [sjtuplayer/anomalydiffusion#53]
请问在训练和推理过程中，除了异常之外的区域是如何利用的呢？

**Comment by sjtuplayer** [comment]
训练和测试的过程可以看做是一个inpainting的学习过程，模型通过观察外围的情况，去学习一个文本向量拟合内部的缺陷。在测试阶段， 缺陷外部直接来源于正常样本，而内部则由学到的文本向量去生成对应的缺陷
