### ISSUE TITLE
感谢您的开源，我有一个代码问题。

### ISSUE THREAD

**Issue by duanyuanyi** [sjtuplayer/anomalydiffusion#54]
论文中每类异常生成1000个样本，对应异常定位代码的dataset = MVTec_Anomaly_Detection(args,obj_name,length=500)，中的length设为了多少？

**Comment by sjtuplayer** [comment]
> 论文中每类异常生成1000个样本，对应异常定位代码的dataset = MVTec_Anomaly_Detection(args,obj_name,length=500)，中的length设为了多少？

你好，这个length只是用来决定Dataset的size，防止每个epoch的数据过少，所以按照默认设置就好，跟具体数据的数量无关
