### ISSUE TITLE
关于提供的生成数据集的相关问题

### ISSUE THREAD

**Issue by duanyuanyi** [sjtuplayer/anomalydiffusion#55]
训练使用前1/3的异常，但是您提供的生成数据集的牙刷中却有黄色和红色，这属于后2/3，这是什么原因呢

**Comment by sjtuplayer** [comment]
> 训练使用前1/3的异常，但是您提供的生成数据集的牙刷中却有黄色和红色，这属于后2/3，这是什么原因呢

你好，仔细观察mvtec数据集数据集的话会发现，里面有些缺陷类别的缺陷表现是不一致的，比如你提到的toothbrush，对于这些类别，他们前1/3的缺陷几乎是一致的，而后2/3的缺陷完全不同，这应该是数据收集时为了规整而安排的，这不太符合缺陷数据随机出现的假设。因此，对于这种数据，我们是用的随机采样1/3的方案来实现的（这种类别太少，属于特例了，所以为了不破坏1/3的setting，没有单独提出来）。为了避免后续研究时遇到相似的问题，我们重新检查了数据集设置，同样有该情况的缺陷类别有toothbrush-defective,cable-swap与metal_nut-color，可以适当注意一下这些类别。但是因为这个类别确实比较少，整体上对结果指标的影响并不大。

**Comment by Musawar71** [comment]
Dear Hu Teng,

@duanyuanyi says that: why the foreground has red and yellow toothbrushes. Because, for anomaly generation you pick random images from good images to get the fake defective image. So it can be any color however, if you changed the splits for specific classes thanks for communicating.
