### ISSUE TITLE
关于下载的生成数据集的问题

### ISSUE THREAD

**Issue by boxbox2** [sjtuplayer/anomalydiffusion#59]
我在data_loader.py发现加载的生成图片都是png格式，
```
        if base_dir == 'good':
            image, mask = self.transform_image(img_path, None)
            has_anomaly = np.array([0], dtype=np.float32)
        else:
            mask_path = os.path.join(dir_path, '../../ground_truth/')
            mask_path = os.path.join(mask_path, base_dir)
            if 'mvtec' in img_path:
                mask_file_name = file_name.split(".")[0]+"_mask.png"
            else:
                mask_file_name = file_name.split(".")[0] + ".png"
            mask_path = os.path.join(mask_path, mask_file_name)
```
可我在提供的谷歌云中生成数据集发现图片都是jpg格式，请问我是在代码中直接将```.png```改成```.jpg```还是将生成数据的后缀都改成```.png```？请问前者的解决方法对模型训练有影响吗？

**Comment by sjtuplayer** [comment]
> 我在data_loader.py发现加载的生成图片都是png格式，
> 
> ```
>         if base_dir == 'good':
>             image, mask = self.transform_image(img_path, None)
>             has_anomaly = np.array([0], dtype=np.float32)
>         else:
>             mask_path = os.path.join(dir_path, '../../ground_truth/')
>             mask_path = os.path.join(mask_path, base_dir)
>             if 'mvtec' in img_path:
>                 mask_file_name = file_name.split(".")[0]+"_mask.png"
>             else:
>                 mask_file_name = file_name.split(".")[0] + ".png"
>             mask_path = os.path.join(mask_path, mask_file_name)
> ```
> 
> 可我在提供的谷歌云中生成数据集发现图片都是jpg格式，请问我是在代码中直接将`.png`改成`.jpg`还是将生成数据的后缀都改成`.png`？请问前者的解决方法对模型训练有影响吗？

你好，这是测试mvtec原始数据集的Dataset，所以是png格式没问题的
