### ISSUE TITLE
About GPU and training time

### ISSUE THREAD

**Issue by chaunceywx** [sjtuplayer/anomalydiffusion#65]
I want to ask how many GPUs and how much time do you used to train your model?

**Comment by Colorful12** [comment]
Hi, if you find the answer to your question, I would appreciate it if you could let me know.

**Comment by chaunceywx** [comment]
> Hi, if you find the answer to your question, I would appreciate it if you could let me know.

https://github.com/sjtuplayer/anomalydiffusion/issues/27#issuecomment-2014220443

**Comment by Colorful12** [comment]
Thank you!
