### ISSUE TITLE
Question about basic Training Details

### ISSUE THREAD

**Issue by jmlee99o** [sjtuplayer/anomalydiffusion#72]
Thanks for your model. I utilize that in my research a lot. : )

I'm just curious about the total epochs of the training.
I can't find about that informations.
Thank you!

**Comment by sjtuplayer** [comment]
the total iteration is 1000000, which can be referred in: https://github.com/sjtuplayer/anomalydiffusion/blob/b85297f333ebfc59b3863338445b81363efb9761/configs/latent-diffusion/txt2img-1p4B-finetune-encoder%2Bembedding.yaml#L119C16-L119C23
