### ISSUE TITLE
Reason of loading anomaly data in dataload

### ISSUE THREAD

**Issue by hy-yhson** [sjtuplayer/anomalydiffusion#79]
Dear author,

Hello, thank you for your amazing work.
I have a question regarding the Personalized_mvtec_encoder dataloader, which loads anomaly images and corresponding masks. 
I would like to inquire about where these elements are utilized within the overall framework.
Thank you for your reply.

**Comment by sjtuplayer** [comment]
> Dear author,
> 
> Hello, thank you for your amazing work. I have a question regarding the Personalized_mvtec_encoder dataloader, which loads anomaly images and corresponding masks. I would like to inquire about where these elements are utilized within the overall framework. Thank you for your reply.

It is employed to train both the spatial encoder and the anomaly embedding, which corresponds to the first stage
