### ISSUE TITLE
关于如何控制瑕疵生成的类型和位置

### ISSUE THREAD

**Issue by Chris-926** [sjtuplayer/anomalydiffusion#81]
您好 首先感谢您愿意拨空看这则问题

在论文中有提到 可以透过Spatial Anomaly Embedding 来去控制生成出瑕疵的类别和位置

想请问一下 具体是透过修改程式中哪一部分 来达到这个效果

再麻烦解答了 谢谢

**Comment by sjtuplayer** [comment]
生成的mask自动存储在./generated_mask/sample_name/anomaly_name（参见https://github.com/sjtuplayer/anomalydiffusion/blob/b85297f333ebfc59b3863338445b81363efb9761/generate_mask.py#L117C2-L117C63 ）
只需要将指定的mask存在该路径下，然后运行generate_with_mask.py即可（注意修改一下对应的sample name和anomaly name，即样本名称和缺陷名称）

**Comment by Chris-926** [comment]
谢谢您的回答

这边还想再问一下 论文中有说 Spatial Anomaly Enbedding e 分为Anomaly Embedding Ea 和 Spatial Embedding Es 分别去控制瑕疵的外观和位置

那想请问一下 这两个部分的Vector是在程式中的哪个部份去做计算的
是位于ldm/modules/embedding_manager2.py里面吗

如果不是的话 那是在哪个py档里去做计算的呢?

再麻烦解答了 谢谢!

**Comment by sjtuplayer** [comment]
> 谢谢您的回答
> 
> 这边还想再问一下 论文中有说 Spatial Anomaly Enbedding e 分为Anomaly Embedding Ea 和 Spatial Embedding Es 分别去控制瑕疵的外观和位置
> 
> 那想请问一下 这两个部分的Vector是在程式中的哪个部份去做计算的 是位于ldm/modules/embedding_manager2.py里面吗
> 
> 如果不是的话 那是在哪个py档里去做计算的呢?
> 
> 再麻烦解答了 谢谢!

可以参考一下这里的代码：https://github.com/sjtuplayer/anomalydiffusion/blob/b85297f333ebfc59b3863338445b81363efb9761/generate_with_mask.py#L140C23-L140C125

**Comment by Chris-926** [comment]
谢谢您的回答

这边还有个问题 想再请教一下

在问题区有看到您回答 其他讀者关于 embedding.pt显示的长度为 [4, 1280] 跟论文不符合的问题

您在回答中提到 提供的 embedding.pt 是正确的，因为长度对结果的影响非常小。可以直接使用它。

那这样我可以理解为 程式出来的结果 anomaly embedding 的 token = 4, spatial embedding 的 token = 4, 而它们concatenate后的token = 8吗

不知我的理解是否正确 如果有误再麻烦纠正了 谢谢 不胜感激!

**Comment by sjtuplayer** [comment]
> 谢谢您的回答
> 
> 这边还有个问题 想再请教一下
> 
> 在问题区有看到您回答 其他讀者关于 embedding.pt显示的长度为 [4, 1280] 跟论文不符合的问题
> 
> 您在回答中提到 提供的 embedding.pt 是正确的，因为长度对结果的影响非常小。可以直接使用它。
> 
> 那这样我可以理解为 程式出来的结果 anomaly embedding 的 token = 4, spatial embedding 的 token = 4, 而它们concatenate后的token = 8吗
> 
> 不知我的理解是否正确 如果有误再麻烦纠正了 谢谢 不胜感激!

是的，直接将两个token序列拼接到了一起，长度相加即可

**Comment by Chris-926** [comment]
非常感谢您的回答!!
