### ISSUE TITLE
如何使用其他数据集进行异常合成

### ISSUE THREAD

**Issue by Excy-an** [sjtuplayer/anomalydiffusion#82]
作者您好，想咨询一下这个工作是只能针对MTvec数据集吗，如果更换其他数据集应该怎么操作呢

**Comment by TonightATiger** [comment]
up

**Comment by sjtuplayer** [comment]
It supports custom datasets. Just keep the dataset structure the same as MVTec and design your own name-anomaly.txt according to your dataset.
