### ISSUE TITLE
tile 的crack类别生成效果很差

### ISSUE THREAD

**Issue by gongjizhang** [sjtuplayer/anomalydiffusion#84]
![image](https://github.com/user-attachments/assets/bb98ced6-a58c-48fc-a21a-2c28aff78eb4)
tile 的crack类别生成效果很差，大家实验结果也是这样吗？

**Comment by linkenfaqiu** [comment]
是的。。不过我看作者提供的generated_dataset里的效果也不好

**Comment by sjtuplayer** [comment]
> ![image](https://private-user-images.githubusercontent.com/22426561/382226989-bb98ced6-a58c-48fc-a21a-2c28aff78eb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MTkwMzQsIm5iZiI6MTczMDcxODczNCwicGF0aCI6Ii8yMjQyNjU2MS8zODIyMjY5ODktYmI5OGNlZDYtYTU4Yy00OGZjLWEyMWEtMmMyOGFmZjc4ZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDExMTIxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0NzQxZGNjNWU4M2RiZDRmNDk3YzY1MDU4YmM0YzBmNDQ0M2NjOTljOGU1MGY2NGUzYjNlNTE5ZDBjYThiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.tD-61wCbl9-LQ4sOj91vFgMlSaYMHCgPPyhc-YjtH1c) tile 的crack类别生成效果很差，大家实验结果也是这样吗？

AnomalyDiffusion在某些比较小或者细的缺陷上表现并不能很好，可以参考一下提供的generated dataset
