### ISSUE TITLE
if it supports custom datasets???

### ISSUE THREAD

**Issue by TonightATiger** [sjtuplayer/anomalydiffusion#85]
Hello, author 
May I ask if this project is specifically prepared for the MVTEC dataset and if it supports custom datasets?

ths!

**Comment by sjtuplayer** [comment]
It supports custom datasets. Just keep the dataset structure the same as MVTec and design your own name-anomaly.txt according to your dataset.

**Comment by TonightATiger** [comment]
> It supports custom datasets. Just keep the dataset structure the same as MVTec and design your own name-anomaly.txt according to your dataset.

Ok,i got it.Thank you for  your reply!
