### ISSUE TITLE
Pillow的版本问题

### ISSUE THREAD

**Issue by zqxie77** [sjtuplayer/anomalydiffusion#87]
报以下错误ANTIALIAS = Image.Resampling.LANCZOS
[rank0]:   File "/envs/Anomalydiffusion/lib/python3.8/site-packages/PIL/Image.py", line 77, in __getattr__
[rank0]:     raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
[rank0]: AttributeError: module 'PIL.Image' has no attribute 'Resampling'
[rank0]:[W1109 16:45:30.321288529 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())

或者

Traceback (most recent call last): File "main.py", line 814, in <module> data.prepare_data() File "anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 474, in wrapped_fn fn(*args, **kwargs) File "/anomalydiffusion/main.py", line 297, in prepare_data instantiate_from_config(data_cfg) File "/homeanomalydiffusion/ldm/util.py", line 86, in instantiate_from_config return get_obj_from_str(config["target"])(**config.get("params", dict()), **kwargs) File "/home/anomalydiffusion/ldm/data/personalized.py", line 167, in __init__ self.interpolation = {"linear": PIL.Image.LINEAR, AttributeError: module 'PIL.Image' has no attribute 'LINEAR'

请问作者用的版本是哪个呀

**Comment by zqxie77** [comment]
DDIM Sampler: 100%|████████████████████████████████████████████████████████████████████████| 200/200 [00:07<00:00, 28.04it/s]
Summoning checkpoint.██████████████████████████████████████████████████████████████████████| 200/200 [00:07<00:00, 28.13it/s]

[rank0]: Traceback (most recent call last):
[rank0]:   File "main.py", line 872, in <module>
[rank0]:     trainer.fit(model, data)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 735, in fit
[rank0]:     self._call_and_handle_interrupt(
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 682, in _call_and_handle_interrupt
[rank0]:     return trainer_fn(*args, **kwargs)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 770, in _fit_impl
[rank0]:     self._run(model, ckpt_path=ckpt_path)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1193, in _run
[rank0]:     self._dispatch()
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1272, in _dispatch
[rank0]:     self.training_type_plugin.start_training(self)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 202, in start_training
[rank0]:     self._results = trainer.run_stage()
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1282, in run_stage
[rank0]:     return self._run_train()
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1312, in _run_train
[rank0]:     self.fit_loop.run()
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
[rank0]:     self.advance(*args, **kwargs)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 234, in advance
[rank0]:     self.epoch_loop.run(data_fetcher)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 145, in run
[rank0]:     self.advance(*args, **kwargs)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 220, in advance
[rank0]:     self.trainer.call_hook("on_train_batch_end", batch_end_outputs, batch, batch_idx, **extra_kwargs)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1477, in call_hook
[rank0]:     callback_fx(*args, **kwargs)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/trainer/callback_hook.py", line 179, in on_train_batch_end
[rank0]:     callback.on_train_batch_end(self, self.lightning_module, outputs, batch, batch_idx, 0)
[rank0]:   File "/home /anomalydiffusion/main.py", line 506, in on_train_batch_end
[rank0]:     self.log_img(pl_module, batch, batch_idx, split="train")
[rank0]:   File "/home /anomalydiffusion/main.py", line 488, in log_img
[rank0]:     logger_log_images(pl_module, images, pl_module.global_step, split)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/pytorch_lightning/utilities/distributed.py", line 49, in wrapped_fn
[rank0]:     return fn(*args, **kwargs)
[rank0]:   File "/home /anomalydiffusion/main.py", line 432, in _testtube
[rank0]:     pl_module.logger.experiment.add_image(
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/torch/utils/tensorboard/writer.py", line 625, in add_image
[rank0]:     image(tag, img_tensor, dataformats=dataformats), global_step, walltime
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 577, in image
[rank0]:     image = make_image(tensor, rescale=rescale)
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/torch/utils/tensorboard/summary.py", line 625, in make_image
[rank0]:     ANTIALIAS = Image.Resampling.LANCZOS
[rank0]:   File "/home /app/anaconda3/envs/Anomalydiffusion/lib/python3.8/site-packages/PIL/Image.py", line 77, in __getattr__
[rank0]:     raise AttributeError(f"module '{__name__}' has no attribute '{name}'")
[rank0]: AttributeError: module 'PIL.Image' has no attribute 'Resampling'
[rank0]:[W1109 16:59:43.468932620 ProcessGroupNCCL.cpp:1168] Warning: WARNING: process group has NOT been destroyed before we destruct ProcessGroupNCCL. On normal program exit, the application should call destroy_process_group to ensure that any pending NCCL operations have finished in this process. In rare cases this process can exit before this point and block the progress of another member of the process group. This constraint has always been present,  but this warning has only been added since PyTorch 2.4 (function operator())         完整版

**Comment by Wznnnnn** [comment]
我把Pillow从10.4.0 降到 9.5.0 是可以跑通train的代码了
